### ISSUE TITLE
Making readme file more attractive and informative

### ISSUE THREAD

**Issue by anshulhub** [anshulhub/My-Editter#4]

**Comment by weicheansoo** [comment]
Hi, can I do this? Also are there any requirements as to what to add to the readme?

**Comment by anshulhub** [comment]
@weicheansoo yes,please try..i want you to make the readme file more informative by providing information about all functionalities and making it easy and attractive to read by adding few images related to the project.

**Comment by weicheansoo** [comment]
All right, I will start working on it!

**Comment by msmaitran** [comment]
Is this available to work on?

**Comment by TheTechRobo** [comment]
If I'm correct it's already finished! You can still contribute if you want.

**Comment by anshulhub** [comment]
> Is this available to work on?

New ideas and contributions are always welcomed!

**Comment by weicheansoo** [comment]
Hi, I wanted to ask if there were any licenses that should be included in the readme as well?

**Comment by anshulhub** [comment]
> Hi, I wanted to ask if there were any licenses that should be included in the readme as well?
You can send me a sample for consideration.

**Comment by weicheansoo** [comment]
Something like the MIT License, which is Open Source. Link: [https://opensource.org/licenses/MIT]

**Comment by anshulhub** [comment]
> Something like the MIT License, which is Open Source. Link: [https://opensource.org/licenses/MIT]

please include it accurately in the readme itself and push request.

**Comment by weicheansoo** [comment]
Noted, will work on it soon!

**Comment by anshulhub** [comment]
resolved
